// Generated by CoffeeScript 1.6.3
var HandlebarsCompiler, handlebars, sysPath;

handlebars = require('handlebars');

sysPath = require('path');

module.exports = HandlebarsCompiler = (function() {
  HandlebarsCompiler.prototype.brunchPlugin = true;

  HandlebarsCompiler.prototype.type = 'template';

  HandlebarsCompiler.prototype.extension = 'hbs';

  HandlebarsCompiler.prototype.pattern = /\.(?:hbs|handlebars)$/;

  function HandlebarsCompiler(config) {
    this.config = config;
    null;
  }

  HandlebarsCompiler.prototype.compile = function(data, path, callback) {
    var content, err, error, result;
    data = data.replace(/<!--[^>]*-->/gm, '').replace(/\r/gm, "\n").replace(/^\s+|\s+$/gm, "").replace(/\n+/gm, "\n");
    try {
      content = handlebars.precompile(data);
      return result = "module.exports = Handlebars.template(" + content + ");";
    } catch (_error) {
      err = _error;
      return error = err;
    } finally {
      callback(error, result);
    }
  };

  HandlebarsCompiler.prototype.include = [sysPath.join(__dirname, '..', 'vendor', 'handlebars.runtime-1.0.rc.1.js')];

  return HandlebarsCompiler;

})();
